spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  application:
    name: mybatis-test
logging:
  config: classpath:logback-spring.xml
info: # 自定义属性及信息
  code: test-mybatis
  body: demo111
mybatis-plus:
  typeAliasesPackage: com.example.demo.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    lazy-loading-enabled: true
    use-column-label: true
    call-setters-on-nulls: true
    multiple-result-sets-enabled: true
    map-underscore-to-camel-case: true
    default-executor-type: reuse
    default-statement-timeout: 25000
  global-config:
    db-config:
      #表名下划线命名默认true
      table-underline: true
      #id类型
      id-type: assign_uuid
  type-enums-package: com.example.demo.enumeration
management:
  endpoints:
    web:
      exposure:
        include: "*"  #开放所有的接口监听
